export const mockHousesArray = [
  { 
    ancestralWeapons: ["Lady Forlorn"],
    cadetBranches: [],
    coatOfArms: "Three black ravens in flight, holding three red hearts, on a white field(Argent, three ravens volant sable, each clutching in their claws a heart gules)",
    currentLord: "https://www.anapioficeandfire.com/api/characters/681",
    diedOut: "",
    founded: "",
    founder: "https://www.anapioficeandfire.com/api/characters/256",
    heir: "https://www.anapioficeandfire.com/api/characters/677",
    name: "House Corbray of Heart's Home",
    overlord: "https://www.anapioficeandfire.com/api/houses/7",
    region: "",
    seats: ["Heart's Home"],
    swornMembers: (8) ["https://www.anapioficeandfire.com/api/characters/255", "https://www.anapioficeandfire.com/api/characters/256", "https://www.anapioficeandfire.com/api/characters/447", "https://www.anapioficeandfire.com/api/characters/654", "https://www.anapioficeandfire.com/api/characters/677", "https://www.anapioficeandfire.com/api/characters/681", "https://www.anapioficeandfire.com/api/characters/871", "https://www.anapioficeandfire.com/api/characters/1182"],
    titles: (2) ["Lord of Heart's Home", "King of the Fingers (historical)"],
    url: "https://www.anapioficeandfire.com/api/houses/81",
    words: "",
  },
  { 
    ancestralWeapons: ["Lady Forlorn"],
    cadetBranches: [],
    coatOfArms: "Three black ravens in flight, holding three red hearts, on a white field(Argent, three ravens volant sable, each clutching in their claws a heart gules)",
    currentLord: "https://www.anapioficeandfire.com/api/characters/681",
    diedOut: "",
    founded: "",
    founder: "https://www.anapioficeandfire.com/api/characters/256",
    heir: "https://www.anapioficeandfire.com/api/characters/677",
    name: "House Corbray of Heart's Home",
    overlord: "https://www.anapioficeandfire.com/api/houses/7",
    region: "",
    seats: ["Heart's Home"],
    swornMembers: (8) ["https://www.anapioficeandfire.com/api/characters/255", "https://www.anapioficeandfire.com/api/characters/256", "https://www.anapioficeandfire.com/api/characters/447", "https://www.anapioficeandfire.com/api/characters/654", "https://www.anapioficeandfire.com/api/characters/677", "https://www.anapioficeandfire.com/api/characters/681", "https://www.anapioficeandfire.com/api/characters/871", "https://www.anapioficeandfire.com/api/characters/1182"],
    titles: (2) ["Lord of Heart's Home", "King of the Fingers (historical)"],
    url: "https://www.anapioficeandfire.com/api/houses/81",
    words: "",
  }  
]

const mockHousesAction = {houses: [
    { 
      ancestralWeapons: ["Lady Forlorn"],
      cadetBranches: [],
      coatOfArms: "Three black ravens in flight, holding three red hearts, on a white field(Argent, three ravens volant sable, each clutching in their claws a heart gules)",
      currentLord: "https://www.anapioficeandfire.com/api/characters/681",
      diedOut: "",
      founded: "",
      founder: "https://www.anapioficeandfire.com/api/characters/256",
      heir: "https://www.anapioficeandfire.com/api/characters/677",
      name: "House Corbray of Heart's Home",
      overlord: "https://www.anapioficeandfire.com/api/houses/7",
      region: "",
      seats: ["Heart's Home"],
      swornMembers: (8) ["https://www.anapioficeandfire.com/api/characters/255", "https://www.anapioficeandfire.com/api/characters/256", "https://www.anapioficeandfire.com/api/characters/447", "https://www.anapioficeandfire.com/api/characters/654", "https://www.anapioficeandfire.com/api/characters/677", "https://www.anapioficeandfire.com/api/characters/681", "https://www.anapioficeandfire.com/api/characters/871", "https://www.anapioficeandfire.com/api/characters/1182"],
      titles: (2) ["Lord of Heart's Home", "King of the Fingers (historical)"],
      url: "https://www.anapioficeandfire.com/api/houses/81",
      words: "",
    },
    { 
      ancestralWeapons: ["Lady Forlorn"],
      cadetBranches: [],
      coatOfArms: "Three black ravens in flight, holding three red hearts, on a white field(Argent, three ravens volant sable, each clutching in their claws a heart gules)",
      currentLord: "https://www.anapioficeandfire.com/api/characters/681",
      diedOut: "",
      founded: "",
      founder: "https://www.anapioficeandfire.com/api/characters/256",
      heir: "https://www.anapioficeandfire.com/api/characters/677",
      name: "House Corbray of Heart's Home",
      overlord: "https://www.anapioficeandfire.com/api/houses/7",
      region: "",
      seats: ["Heart's Home"],
      swornMembers: (8) ["https://www.anapioficeandfire.com/api/characters/255", "https://www.anapioficeandfire.com/api/characters/256", "https://www.anapioficeandfire.com/api/characters/447", "https://www.anapioficeandfire.com/api/characters/654", "https://www.anapioficeandfire.com/api/characters/677", "https://www.anapioficeandfire.com/api/characters/681", "https://www.anapioficeandfire.com/api/characters/871", "https://www.anapioficeandfire.com/api/characters/1182"],
      titles: (2) ["Lord of Heart's Home", "King of the Fingers (historical)"],
      url: "https://www.anapioficeandfire.com/api/houses/81",
      words: "",
    }  
  ]
}

export const mockCardWithSwornMembers = { 
  ancestralWeapons: ["Lady Forlorn"],
  cadetBranches: [],
  coatOfArms: "Three black ravens in flight, holding three red hearts, on a white field(Argent, three ravens volant sable, each clutching in their claws a heart gules)",
  currentLord: "https://www.anapioficeandfire.com/api/characters/681",
  diedOut: "",
  founded: "",
  founder: "https://www.anapioficeandfire.com/api/characters/256",
  heir: "https://www.anapioficeandfire.com/api/characters/677",
  name: "House Corbray of Heart's Home",
  overlord: "https://www.anapioficeandfire.com/api/houses/7",
  region: "",
  seats: ["Heart's Home"],
  swornMembers: [
    {url: "https://www.anapioficeandfire.com/api/characters/255", name: "Corwyn Corbray", gender: "Male", culture: "", born: ""},
    {url: "https://www.anapioficeandfire.com/api/characters/256", name: "Corwyn Corbray", gender: "Male", culture: "Andal", born: ""},
    {url: "https://www.anapioficeandfire.com/api/characters/447", name: "Gwayne Corbray", gender: "Male", culture: "", born: ""},
    {url: "https://www.anapioficeandfire.com/api/characters/654", name: "Lucas Corbray", gender: "Male", culture: "", born: ""},
    {url: "https://www.anapioficeandfire.com/api/characters/677", name: "Lyn Corbray", gender: "Male", culture: "", born: "At Heart's Home"},
    {url: "https://www.anapioficeandfire.com/api/characters/681", name: "Lyonel Corbray", gender: "Male", culture: "", born: "In 260 AC (roughly), at Heart's Home"},
    {url: "https://www.anapioficeandfire.com/api/characters/871", name: "Rhaena Targaryen", gender: "Female", culture: "", born: "In 116 AC, at Pentos"},
    {url: "https://www.anapioficeandfire.com/api/characters/1182", name: "Baelish", gender: "Male", culture: "Braavosi", born: ""}
  ],
  titles: (2) ["Lord of Heart's Home", "King of the Fingers (historical)"],
  url: "https://www.anapioficeandfire.com/api/houses/81",
  words: "",
}


